#!/bin/bash

set -e

if [[ "${TRAVIS_BRANCH}"        == "master"            &&
      "${TRAVIS_REPO_SLUG}"     == "bokeh/bokeh-scala" &&
      "${TRAVIS_JDK_VERSION}"   == "oraclejdk8"        &&
      "${TRAVIS_PULL_REQUEST}"  == "false"             ]];
then
    ./sbt ++$TRAVIS_SCALA_VERSION upload
fi
