#!/bin/bash

set -e

if [[ "${TRAVIS_BRANCH}"        == "master"            &&
      "${TRAVIS_REPO_SLUG}"     == "bokeh/bokeh-scala" &&
      "${TRAVIS_JDK_VERSION}"   == "oraclejdk7"        &&
      "${TRAVIS_PULL_REQUEST}"  == "false"             ]];
then
    sudo apt-get install -qq -y python python-pip
    sudo pip install -q awscli
    ./sbt ++$TRAVIS_SCALA_VERSION upload
fi
